Release/3.0.0
opentensor/btwallet pull request #81
Opened 2024-12-18 17:07 UTC by ibraheem-opentensor

## 3.0.0 /2024-12-18

## What's Changed
* Feat/wallet lib by @distributedstatemachine, @keithtensor, @ibraheem-opentensor in https://github.com/opentensor/btwallet/pull/73

## New Contributors
* @distributedstatemachine made their first contribution in https://github.com/opentensor/btwallet/pull/73
* @keithtensor made their first contribution in https://github.com/opentensor/btwallet/pull/73

**Full Changelog**: https://github.com/opentensor/btwallet/compare/v2.1.3...v3.0.0

2024-12-23 16:25 UTC, keithtensor approved these changes

2025-01-08 14:49 UTC, roman-opentensor requested changes
Pls add this PR https://github.com/opentensor/btwallet/pull/82 into this release

2025-01-15 19:36 UTC, roman-opentensor approved these changes

2025-01-15 20:24 UTC, camfairchild approved these changes

2025-01-15 20:29 UTC, merged